apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values: ["ssd"]
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Running with Node Affinity' && sleep 3600"]
