

apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-1
  labels:
    app: myapp
spec:
  nodeName: my-cluster-worker
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-2
  labels:
    app: myapp
spec:
  nodeName: my-cluster-worker2
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-3
  labels:
    app: myapp
spec:
  nodeName: my-cluster-worker3
  containers:
  - name: nginx
    image: nginx

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: myapp
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx
