apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Enable stub_status for metrics
        location /stub_status {
            stub_status on;
            allow 127.0.0.1;
            allow ::1;
            deny all;
        }

        error_page 404 /404.html;
        location = /404.html {
            root /usr/share/nginx/html;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
