apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5

  - name: sidecar
    image: busybox
    command: ["/bin/sh", "-c", "trap 'exit 0' SIGTERM; while true; do sleep 1; done"]
