apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.db.storage | quote }}
  storageClassName: {{ .Values.apps.db.storageClass | default "managed-csi" }}
